run-name: aws-lc-rs sanity tests
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./aws-lc
      - uses: actions/checkout@v3
        with:
          repository: awslabs/aws-lc-rust
          path: ./aws-lc-rust
          submodules: false
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: |
          sudo apt-get -y --no-install-recommends update
          sudo apt-get -y --no-install-recommends upgrade
          sudo apt-get -y --no-install-recommends install cmake gcc
      - working-directory: ./aws-lc-rust
        run: |
          rm -rf ./aws-lc-sys/aws-lc
          ln -s ../aws-lc ./aws-lc-sys/aws-lc
      - uses: actions-rs/cargo@v1
        working-directory: ./aws-lc-rust/aws-lc-sys
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        working-directory: ./aws-lc-rust/aws-lc-sys
        with:
          command: test
      - uses: actions-rs/cargo@v1
        working-directory: ./aws-lc-rust/aws-lc-sys
        with:
          command: package
      - uses: actions-rs/cargo@v1
        working-directory: ./aws-lc-rust/aws-lc-rust
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        working-directory: ./aws-lc-rust/aws-lc-rust
        with:
          command: test
